### ISSUE TITLE
Error getting package

### ISSUE THREAD

**Issue by AlvoErrado2** [s32x/anirip#22]
When I try to follow this part of the initial instructions --> []https://github.com/s32x/anirip#setup-guide-hard

`$ go get`
`$ go install`

I get the following error in console:
```
Z:\BBB\AAA\go\src\github.com\s32x\anirip\common\httpclient.go:17:2: 
code in directory Z:\BBB\AAA\go\src\github.com\entrik\httpclient expects 
import "s32x.com/httpclient"
```
I can not log in using the compiled binary you have on the page, so I was trying to generate a new one to see if there was a difference.

**Comment by s32x** [comment]
Try again. I have just pushed changes that should fix the dependency issues

**Comment by s32x** [comment]
I also updated the "hard" guide, Try using - `go get s32x.com/anirip`

**Comment by s32x** [comment]
Currently, the app doesn't support custom arguments. The resolution and episode downloads are hardcoded. However, I can easily implement a CLI style command interface that will take arguments for episode, resolution etc. I'll do my best to have this implemented in the next few days.

**Comment by AlvoErrado2** [comment]
I'm waiting for the changes, and there's no need to hurry.

**Comment by s32x** [comment]
I've implemented CLI style formatting. Two flags that are now supported are `--language` and `--quality`. You can see the features by doing a `go get s32x/anirip` and running `anirip --help`. As for the episode selection, I don't have really any plans to implement that soon. For now you'll have to just download the entire show or tweak the source yourself. As for resolution - I think it goes without saying that without having a crunchyroll premium account you won't be able to download any higher than 720.
