### ISSUE TITLE
Can't change video quality

### ISSUE THREAD

**Issue by eco9898** [s32x/anirip#37]
When attempting to use -q to assign quality the video still uses the default (which is the highest available). Judging by a quick look through the code I think this is because the quality isn't passed on to the download function properly

**Comment by s32x** [comment]
Hmm. I remember having issues with the quality flag. Let me look into it and I'll get back to you.

**Comment by theclickman** [comment]
see my note in #47 that may fix the issue (not tested)

**Comment by s32x** [comment]
Hopefully this is taken care of in #49. If not please feel free to re-open!
