### ISSUE TITLE
No Title in Command Prompt

### ISSUE THREAD

**Issue by tasdanduil** [s32x/anirip#40]
![Screenshot (5)](https://user-images.githubusercontent.com/50717769/67527418-d232f800-f66b-11e9-9549-8685d199ca01.png)

The show title used to appear before the season and episode number. The problem with this no longer being the case is that I can't skip episodes I already have anymore. I've tried to rename the files with spaces in front (as there seems to be a space in place of the missing title), but that doesn't seem to work. Any help would be appreciated.

**Comment by tasdanduil** [comment]
When I think about it, if there were a way to download specific episodes individually that would work for the time being.

**Comment by turtletowerz** [comment]
The issue with the title not showing should be fixed in #41 It seems like the html of the webpage changed around slightly which was why it wasn't showing the title.
