### ISSUE TITLE
Subtitles broken

### ISSUE THREAD

**Issue by benjamin238** [s32x/anirip#47]
anirip no longer downloads subtitles. I have tried rebuilding the latest version of anirip, updating ffmpeg, and even updating Go, but nothing seems to work. It doesn't even throw an error, it still says
```
[anirip] Downloading subtitles...
[anirip] Merging subtitles into MKV container...
[anirip] Downloading and merging completed successfully!
```
like it was fine.

**Comment by turtletowerz** [comment]
Can you please provide the command you ran to produce this output? Also what media player are you using to watch the downloaded videos? I had some problems with VLC Media Player on certain occasions

**Comment by benjamin238** [comment]
I used `anirip user pass show`, and I downloaded My Hero Academia and Jojo, neither of which had subtitles in their rips, and later I used Bananya to verify this issue as it's episodes are only three minutes long and took seconds to download. I've used this program in the past to rip Dr. Stone, and it's subtitle track shows up in VLC fine, but downloading the same episode now, it's subtitles aren't showing in the sub track tab. Just to test, I tried to burn the subtitles in using Handbrake, but doesn't work either. Using Handbrake to burn the subtitles of my old rips worked fine.

**Comment by turtletowerz** [comment]
I opened a PR (#48) that should fix this issue.

On a side note, you may begin receiving "Failed to verify session" errors due to Crunchyroll implementing a new re-captcha system. Please do not open a separate issue if you encounter this and instead comment below regarding it

**Comment by benjamin238** [comment]
I just built and tested your patch and it didn't seem to work. I again tried my four test shows, and none of them had sub tracks. I also tried specifying both `en-US` and `enUS` as language codes, but nothing worked.

**Comment by benjamin238** [comment]
It seems like manually setting the ISO code by doing `isoCode := "eng"` worked for me. I'm just going to use my private build for now.

**Comment by turtletowerz** [comment]
Sorry I wasn't able to adequately test it, I still can't verify the session so I haven't been able to test the hotfix

**Comment by theclickman** [comment]
I did find out I was having the same issue, and i think I got what is wrong:

in main.go, function main() you are calling
download(args[2], args[0], args[1], c.String("lang"), c.String("lang"))

But that parameter do not exist. therfore quality and langage value were passed empty.

as per my understanding, it should be
download(args[2], args[0], args[1], c.String("quality"), c.String("language"))
(Yes, the quality was also wrong, that should also fix it, but I did not test this part).

With that fix, I was able to get the subtitle back in the file.

(Note, to debug that, I did add a -report to the ffmpeg command line at the time of the merge, so I was getting debug output of mmpeg in the temp folder. you may want to consider adding a -debug parameter that enable that in the future :) )

**Comment by theclickman** [comment]
note: it still need the hotfix you need to extract "en" from en-US to work.

**Comment by s32x** [comment]
This should be care of in #49. If not please feel free to re-open!
