### ISSUE TITLE
Subtitles change after first episode.

### ISSUE THREAD

**Issue by ckolivas** [s32x/anirip#50]
On testing this on a series with multiple language subtitles, I found the subtitles changed to Spanish after the first episode in English. I added a little debugging to see why that might be and found this:
[anirip] Downloading subtitles...en-US
[anirip] Downloaded subtitles...en
It appears the variable subLang loses the "-US" extension after the function call:
subLang, err = episode.DownloadSubtitles(client, subLang, tempDir)
which creates the problem.

**Comment by ckolivas** [comment]
Submitted a pull request to address this:
https://github.com/s32x/anirip/pull/52

**Comment by s32x** [comment]
Good work man. Thanks again.
