### ISSUE TITLE
Doesn´t work because of your stupid redirects...

### ISSUE THREAD

**Issue by Schnabelriechen** [s32x/anirip#54]
Instead of directly linking to the github page, everything has to go though your personal domain (s32x.com), which is broken
"/home/username/go/src/s32x.com/anirip/crunchyroll/subtitle.go:44:13: undefined: strings.ReplaceAll"
Is there any valid reason why doing this shit?

**Comment by s32x** [comment]
Yep, If I ever decide to move off of github the redirects help! Thanks for asking.

**Comment by s32x** [comment]
Judging by the error it doesn't even seem to be related to my redirects at all. Good luck figuring it out

**Comment by turtletowerz** [comment]
It's possible his go version is outdated. `ReplaceAll` was added in 1.12 so maybe you have a version before that?

To check, run `go version`, and verify it's >= 1.12
