### ISSUE TITLE
Error: validating session: &{%!w(string=could not verify session)}

### ISSUE THREAD

**Issue by tasdanduil** [s32x/anirip#55]
![Screenshot (29)0](https://user-images.githubusercontent.com/50717769/74682813-fd41da00-517b-11ea-827b-9abc8035edac.png)
This was working fine earlier today. I did change my password since receiving several emails about my account being accessed. Any suggestions on how to fix this?

**Comment by tasdanduil** [comment]
The problem seems to have solved itself, though I'm not quite sure how or why.

**Comment by turtletowerz** [comment]
I notice this happening occasionally as well. I believe it's because Crunchyroll sometimes enables reCAPTCHA, which causes the login process to fail. Most of the time this is disabled, so it doesn't affect downloading _usually_.
